<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3" Version="3.1.0" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.0.4" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing" Version="1.1.2"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.0.0"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0"/>
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.2" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.10" />
        <PackageReference Include="FluentValidation" Version="12.1.0" />
        <PackageReference Include="OneOf" Version="3.0.271"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\SimpleTrading.Domain.Generators\SimpleTrading.Domain.Generators.csproj">
            <PrivateAssets>All</PrivateAssets>
            <ReferenceOutputAssembly>true</ReferenceOutputAssembly>
            <OutputItemType>Analyzer</OutputItemType>
        </ProjectReference>
    </ItemGroup>

</Project>
