<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\SimpleTrading.Domain\SimpleTrading.Domain.csproj"/>
        <ProjectReference Include="..\..\src\SimpleTrading.WebApi\SimpleTrading.WebApi.csproj"/>
        <ProjectReference Include="..\SimpleTrading.TestInfrastructure\SimpleTrading.TestInfrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3" Version="3.0.1" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="17.14.2"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>
</Project>