//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTrading.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SimpleTradingStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SimpleTradingStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleTrading.Domain.Resources.SimpleTradingStrings", typeof(SimpleTradingStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        public static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilanz.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Ergebnis muss &apos;Kostendeckend&apos; sein, wenn die Bilanz gleich Null ist..
        /// </summary>
        public static string BreakEvenIfBalanceIsZero {
            get {
                return ResourceManager.GetString("BreakEvenIfBalanceIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Währung.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstiegspreis.
        /// </summary>
        public static string EntryPrice {
            get {
                return ResourceManager.GetString("EntryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausstiegspreis.
        /// </summary>
        public static string ExitPrice {
            get {
                return ResourceManager.GetString("ExitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beendet.
        /// </summary>
        public static string FinishedAt {
            get {
                return ResourceManager.GetString("FinishedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Datum &apos;Beendet&apos; kann maximal nur einen Tag in der Zukunft liegen..
        /// </summary>
        public static string FinishedAtTooFarInTheFuture {
            get {
                return ResourceManager.GetString("FinishedAtTooFarInTheFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Datum &apos;Beendet&apos; muss nach dem Datum &apos;Eröffnet&apos; liegen..
        /// </summary>
        public static string FinishedBeforeOpenedError {
            get {
                return ResourceManager.GetString("FinishedBeforeOpenedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um einen beendeten Trade hinzuzufügen, müssen Sie &apos;Beendet&apos;, &apos;Bilanz&apos;, &apos;Ausstiegspreis&apos; und &apos;Ergebnis&apos; angeben..
        /// </summary>
        public static string FinishedTradeNeedsFinishedBalanceAndResult {
            get {
                return ResourceManager.GetString("FinishedTradeNeedsFinishedBalanceAndResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger Link..
        /// </summary>
        public static string InvalidLink {
            get {
                return ResourceManager.GetString("InvalidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Ergebnis muss &apos;Verlust&apos; sein, wenn die Bilanz kleiner als Null ist..
        /// </summary>
        public static string LossIfBalanceIsLessThanZero {
            get {
                return ResourceManager.GetString("LossIfBalanceIsLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Ergebnis muss &apos;Mittelmäßig&apos; oder &apos;Gewinn&apos; sein, wenn die Bilanz größer als Null ist..
        /// </summary>
        public static string MediocreOrWinIfBalanceAboveZero {
            get {
                return ResourceManager.GetString("MediocreOrWinIfBalanceAboveZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmerkungen.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressource nicht gefunden..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} nicht gefunden..
        /// </summary>
        public static string NotFoundNamed {
            get {
                return ResourceManager.GetString("NotFoundNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eröffnet.
        /// </summary>
        public static string OpenedAt {
            get {
                return ResourceManager.GetString("OpenedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonstiges.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenztyp.
        /// </summary>
        public static string ReferenceType {
            get {
                return ResourceManager.GetString("ReferenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnis.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop-Loss.
        /// </summary>
        public static string StopLoss {
            get {
                return ResourceManager.GetString("StopLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take-Profit.
        /// </summary>
        public static string TakeProfit {
            get {
                return ResourceManager.GetString("TakeProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade.
        /// </summary>
        public static string Trade {
            get {
                return ResourceManager.GetString("Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Trade wurde bereits am &apos;{0}&apos; beendet..
        /// </summary>
        public static string TradeAlreadyFinished {
            get {
                return ResourceManager.GetString("TradeAlreadyFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handelsvolumen.
        /// </summary>
        public static string TradeSize {
            get {
                return ResourceManager.GetString("TradeSize", resourceCulture);
            }
        }
    }
}
