@SimpleTrading_HostAddress = https://localhost:44337

GET {{SimpleTrading_HostAddress}}/home/info
Accept: application/json

###
POST {{SimpleTrading_HostAddress}}/trades/F2CEA6F6-3CE7-40F7-A901-B04A6FEFF5E8/close
Accept: application/json
Content-Type: application/json

{
  "assetId": "0c275c78-0508-4836-81d5-342e2445d60c",
  "profileId": "adf868b2-d0ba-4805-8f05-c813310580af",
  "opened": "2024-08-07T10:26:02.570Z",
  "closed": "2024-08-07T10:26:02.570Z",
  "size": 5000,
  "result": null,
  "balance": 0,
  "currencyId": "dd1f1281-7ec9-450e-8dd8-da1f4eb78629",
  "entryPrice": 1,
  "stopLoss": 0.95,
  "takeProfit": 1.4,
  "exitPrice": 1.2,
  "notes": "Some notes",
  "references": [
    {
      "type": "TradingView",
      "link": "https://www.tradingview.com/x/EttfeAMS/",
      "notes": null
    }
  ]
}