name: CI/CD

on:
  push:
    branches: ["**"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Run Conventional Commits check
        uses: webiny/action-conventional-commits@v1.3.0
        
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup dotnet 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Build
        run: |
          dotnet build

      - name: Test
        env:
          TestIdentity__ClientSecret: ${{ secrets.TESTIDENTITY_CLIENTSECRET }}
        run: |
          dotnet test
