namespace SimpleTrading.Domain.Generators;

public class InteractorProxySourceTemplate(InteractorContext context)
{
    private static readonly IReadOnlyList<string> DefaultNamespaces =
    [
        "System",
        "System.Threading.Tasks",
        "System.Collections.Generic",
        "SimpleTrading.Domain.Infrastructure",
        "Microsoft.Extensions.Logging",
        "OneOf"
    ];

    private readonly string _loggerType = $"ILogger<{context.InteractorProxyName}>";

    private readonly string _requestModelDisplayName = context.RequestModel is null
        ? string.Empty
        : context.RequestModel.GetDisplayName();

    private IEnumerable<string> Namespaces =>
    [
        ..DefaultNamespaces,
        OnValidation("FluentValidation"),
        OnValidation("FluentValidation.Results"),
        context.ResponseModel.ContainingNamespace.ToDisplayString(),
        ..context.ResponseModel.GetAllNamespaces(),
        ..context.ClosedInteractorInterface.GetAllNamespaces(),
        ..context.RequestModel is not null ? context.RequestModel.GetAllNamespaces() : [],
    ];

    private IEnumerable<string> UsingStatements => Namespaces
        .Distinct()
        .Where(x => !string.IsNullOrWhiteSpace(x))
        .Select(x => $"using {x};");

    private string RequestModelParameter => string.IsNullOrWhiteSpace(_requestModelDisplayName)
        ? string.Empty
        : $"{_requestModelDisplayName} requestModel";

    public string GenerateProxy()
    {
        var validatorsType = $"IEnumerable<IValidator<{_requestModelDisplayName}>>";
        var requestModelParameter = RequestModelParameter;

        var responseModelTransformed = context.GetResponseModelTransformed();
        var isResponseModelTransformed = !responseModelTransformed.Equals(context.ResponseModel.GetDisplayName(), StringComparison.Ordinal);

        var interactorInvocation = GetInteractorInvocation(responseModelTransformed, isResponseModelTransformed);

        // lang=C#
        return $$"""
                 //----------------------
                 // <auto-generated>
                 //     Generated using Source Generators
                 // </auto-generated>
                 //----------------------

                 {{string.Join("\n\r", UsingStatements)}}

                 namespace {{context.Interactor.ContainingNamespace.ToDisplayString()}};

                 /// <summary>
                 /// Concrete Interactor <see cref="{{context.Interactor.ToDisplayString()}}"/>
                 /// </summary>
                 public interface {{context.InteractorInterfaceName}}
                 {
                     Task<{{responseModelTransformed}}> Execute({{OnContainsRequestModel(requestModelParameter)}});
                 }

                 public sealed class {{context.InteractorProxyName}} : {{context.InteractorInterfaceName}}
                 {
                     private readonly {{_loggerType}} _logger;
                     private readonly {{context.ClosedInteractorInterface.GetDisplayName()}}  _interactor;
                     {{OnValidation($"private readonly {validatorsType} _validators;")}}
                     
                     public {{context.InteractorProxyName}}(
                              {{_loggerType}} logger,
                              {{context.ClosedInteractorInterface.GetDisplayName()}} interactor{{OnValidation(",")}}
                              {{OnValidation($"{validatorsType} validators")}})
                     {
                         _logger = logger;
                         _interactor = interactor;
                         {{OnValidation("_validators = validators;")}}
                     }

                     public async Task<{{responseModelTransformed}}> Execute({{OnContainsRequestModel(requestModelParameter)}}) 
                     {
                         _logger.LogInformation("Executing {proxy}", "{{context.InteractorProxyName}}");

                        {{OnValidation(
                            // lang=C#
                            $$"""
                               foreach(var validator in _validators) 
                                      {
                                          _logger.LogInformation("Validate {interactorName} with {validator}", "{{context.RequestModel?.Name}}", validator.GetType().Name);
                                          var validationResult = await validator.ValidateAsync(requestModel);
                                          if (!validationResult.IsValid)
                                              return validationResult;
                                      }
                              """)}}

                         {{interactorInvocation}}
                     }
                 }
                 """;
    }

    private string GetInteractorInvocation(string responseModelTransformed, bool isResponseModelTransformed)
    {
        var interactorCall = OnContainsRequestModel("_interactor.Execute(requestModel)", "_interactor.Execute()");

        var easyInteractorInvocation = $"return await {interactorCall};";

        var interactorInvocationWithOneOfTransformation =
            $"return {responseModelTransformed}.FromT0(await {interactorCall});";

        var count = context.ResponseModel.TypeArguments.Length;
        var matchFunctions = string.Join(",\n\r",
            Enumerable.Range(0, count).Select(x => FromOneOf(x, responseModelTransformed)));

        var transformedInteractorInvocation =
            // lang=C#
            $"""
             var result =  await _interactor.Execute(requestModel);
                     return  result.Match<{responseModelTransformed}>({matchFunctions});
             """;

        if (!isResponseModelTransformed)
            return easyInteractorInvocation;

        var interactorInvocation = context.IsResponseModelOneOf
            ? transformedInteractorInvocation
            : context is {IsResponseModelOneOf: false, RequestModel: not null}
                ? interactorInvocationWithOneOfTransformation
                : easyInteractorInvocation;

        return interactorInvocation;
    }

    private string OnContainsRequestModel(string onRequestModelExists, string otherwise = "")
    {
        return context.RequestModel is not null ? onRequestModelExists : otherwise;
    }

    private string OnValidation(string onValidation, string otherwise = "")
    {
        return !context.Validators.IsEmpty ? onValidation : otherwise;
    }

    private static string FromOneOf(int index, string responseModel)
    {
        return $"x => {responseModel}.FromT{index}(x)";
    }
}